steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/cookie-web:develop', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/cookie-web:develop']
  - name: 'asia.gcr.io/$PROJECT_ID/helm'
    args:
      - upgrade
      - becookies-web
      - --install
      - --namespace
      - dev
      - --recreate-pods
      - -f
      - helm/cookie-web/dev.yaml
      - helm/cookie-web/
    env:
      - "CLOUDSDK_CORE_PROJECT=beid-307007"
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"
